---
title: "Lecture 6 - Intro to Logistic Regression"
author: "Waha"
format: html
editor: visual
---

# Logistic Regression

```{r}
library(tidyverse)
library(MASS)
library(ISLR)
library(ISLR2)
library(nnet)
library(e1071)
library(DescTools)
```

# Exercise 1

```{r}
head(Publication)
colnames(Publication)
multi_log <- nnet::multinom(
  formula = mech ~ posres + multi + clinend + sampsize + budget + impact + time + status, 
  data = Publication)

z_stats <- summary(multi_log)$coefficients / summary(multi_log)$standard.errors
p_values <- (1 - pnorm(abs(z_stats)))*2
data.frame(t(p_values))

#Not the best fit, removing sampsize + impact + time should give the best fit. 

mod = multinom(mech ~ posres + multi + clinend + sampsize + budget + impact + time + status, data = Publication, model = TRUE)
PseudoR2(mod)

mod = multinom(mech ~ posres + multi + clinend + budget + status, data = Publication, model = TRUE)
PseudoR2(mod)
```

```{r}
data("Credit")
head(Credit)

## make a dummy for default

Credit|>
  mutate(mark_south = ifelse(Region == "South",1,0), mark_west = ifelse(Region == "West",1,0), mark_east = ifelse(Region == "East",1,0)) -> mark

mod = lm(mark_south ~ Balance, data = mark)|>
  broom::augment()
PseudoR2(mod)

lm(mark_west ~ Balance, data = mark)|>
  broom::augment()
lm(mark_east ~ Balance, data = mark)|>
  broom::augment()

## regress dummy over balance and plot 

lm(mark_south ~ balance, 
   data = def_dum)|>
  broom::augment()|>
  ggplot(aes(balance,default_dumm))+
  geom_point(alpha= 0.6)+
  geom_line(aes(balance, .fitted),
            colour = "red")+
  labs(
    title = "Linear regression fit to qualitative response",
    subtitle = "Yes =1, No = 0",
    y = "prob default status"
  )+
  theme_minimal() -> plot_linear

## Run the logistic regression

glm(
  default_dumm ~ Balance,
  data = mark,
  family = binomial
)|>
  broom::augment(type.predict = "response")|>
  ggplot(aes(balance,default_dumm))+
  geom_point(alpha= 0.6)+
  geom_line(aes(balance, .fitted),
            colour = "red")+
  labs(
    title = "Logistic regression fit to qualitative response",
    subtitle = "Yes =1, No = 0",
    y = "prob default status"
  )+
  theme_minimal() -> logistic_plot
```

```{r}

```

```{r}

```
